part4
mvpurin/Test-Guru pull request #3
Opened 2022-02-04 11:37 UTC by mvpurin

2022-02-04 11:56 UTC, BubuntuClu requested changes

2022-02-04 11:56 UTC, BubuntuClu commented on app/models/test.rb
> +	belongs_to :category
отступы надо поправить. едет код на гитхабе

2022-02-04 11:56 UTC, BubuntuClu commented on db/migrate/20220118150544_create_tests.rb
> +      t.references :user, foreign_key: {on_delete: :cascade}
нельзя править миграции которые вмержены в мастер ветку. убери тут код и через новые миграции добавлять нужные тебе изменения

2022-02-04 11:56 UTC, BubuntuClu commented on app/models/user.rb
> +	has_many :tests
эта не та ассоциация что требуется для этого задания. у тебя связь многие-ко-многим, она реализуется другим способом

2022-02-04 11:56 UTC, BubuntuClu commented on app/models/user.rb
> +		tests.where(level: level)
этот запрос не вернет тесты, которые проходил пользователь

2022-02-09 17:02 UTC, BubuntuClu commented on app/models/test.rb
> +  has_many :users, through: :test_users, dependent: :destroy
1 - dependent: :destroy, ты планируешь удалять всех пользователей проходивших этот тест? жестка
2 - такая опция не работает для ассоциаций с указанием `through`

2022-02-09 18:20 UTC, mvpurin commented on app/models/test.rb
> +  has_many :users, through: :test_users, dependent: :destroy
Видимо, я ещё не разобрался до конца с опцией dependent: :destroy. У меня были проблемы с откатами миграций из-за внешних ключей, а на форумах писали, что это может помочь.

2022-02-14 15:59 UTC, merged