Part8
mvpurin/Test-Guru pull request #8
Opened 2022-04-05 15:41 UTC by mvpurin

2022-04-06 06:40 UTC, BubuntuClu requested changes

2022-04-06 06:40 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    redirect_to action: 'index', test_id: session[:test_id]
`redirect_to test_path(@question.test)`

2022-04-06 06:40 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +      redirect_to action: 'index', test_id: session[:test_id]
почему значение теста ты берешь из сессии?
`redirect_to test_path(@question.test)`

2022-04-06 06:40 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +  def save_session_params
какой толк от этого действия? зачем ты из одного места информацию копируешь еще и в другое?

2022-04-06 06:40 UTC, BubuntuClu commented on app/helpers/questions_helper.rb
> +    if !params[:test_id].nil?
хэлпер для вопроса, поэтому сюда стоит передать вопрос. исопльзуй `new_record?/persisted?` чтобы понять какой заголовок надо отобразить.

2022-04-06 06:40 UTC, BubuntuClu commented on app/helpers/questions_helper.rb
> +      if current_page?(new_test_question_path)
ты же в слаке спросил про текущую страницу, я тебе ответил что не надо так делать

2022-04-06 06:40 UTC, BubuntuClu commented on app/helpers/questions_helper.rb
> +  def current_year
этот и метод ниже не относятя к хэлперам вопроса

2022-04-06 06:40 UTC, BubuntuClu commented on app/helpers/questions_helper.rb
> +    "https://github.com/#{author}/#{repo}"
возвращай сразу хэлпер `link_to`

2022-04-06 06:40 UTC, BubuntuClu commented on app/views/questions/index.html.erb
> +  <style>
почему стиль описывается внутри html тэгов таблицы? надо вынести стили в отдельный файл

2022-04-09 06:23 UTC, mvpurin commented on app/helpers/questions_helper.rb
> +    if !params[:test_id].nil?
`  def question_header(question)
    p "Create New <#{Test.find(@question.test_id).title}> Question" if @question.new_record?
    p "Edit <#{Test.find(@question.test_id).title}> Question" if @question.persisted?
  end`
  Переделал таким образом, метод `edit` работает нормально, но при создании нового вопроса надпись "Create New..." не выводится почему-то. Хотя в консоли я проверил, что `@question.new_record?` возвращает `true`. В чем может быть проблема?

2022-04-11 16:02 UTC, BubuntuClu commented on app/helpers/questions_helper.rb
> +    return "Create New <#{Test.find(@question.test_id).title}> Question" if @question.new_record?
1- использовать надо объект, который ты передал в метод, а не инстан переменную
2- используй ассоциации, а не сам пиши запросы
3- используй `if/else` чтобы не делать две одинаковые проверки
```
if question.new_record?
  "Create New <#{question.test.title}> Question"
else
  "Edit <#{question.test.title}> Question"
end
```

2022-04-11 16:03 UTC, BubuntuClu requested changes

2022-04-11 16:03 UTC, BubuntuClu commented on app/views/questions/edit.html.erb
> +    <%= form.collection_select :test_id, Category.all, :id, :title, prompt: true %>
1 - почему для тестов ты делаешь селектор по катгеориям?
2 - тебе вообще не нужен выбор тестов для вопросов, ты из url параметр берешь

2022-04-11 16:03 UTC, BubuntuClu commented on app/views/questions/edit.html.erb
> +<h1><%= question_header(@question) %></h1>
у тебя вьюхи `new/edit` будут одинаковые. будут вызывать просто рендер `_form`

2022-04-12 06:36 UTC, BubuntuClu commented on app/views/questions/edit.html.erb
>  <h1><%= question_header(@question) %></h1>
эта строка повторяется и в new и в edit. вынеси ее тоже в форму

2022-04-12 06:36 UTC, BubuntuClu commented on app/views/questions/edit.html.erb
> +<%= link_to 'Back', test_questions_path(@question.test_id) %>
эта строка тоже одинаковая для обехи вьюх, она должна быть в форме

2022-04-12 06:36 UTC, BubuntuClu requested changes

2022-04-12 06:36 UTC, BubuntuClu commented on app/helpers/questions_helper.rb
> +      "Create New <#{Test.find(question.test_id).title}> Question"
не заменил на ассоциацию

2022-04-25 12:52 UTC, merged